# 31f6e77ac35c72591511b9fa3e4b8955b0bb22d5
# 0413ba8f59c77e02d6b41a9916960c14b40fc726
blank_issues_enabled: false
contact_links:
  - name: XDA Community Support
    url: https://forum.xda-developers.com/f/AOHH9803252Q5.5903/
    about: Please ask and answer questions here.
